export const ids = {
  kurta: "3f6c1a52-8d4e-4b7a-9c21-5e0b7d9a4f13",
  shoes: "8b2e4d17-1c9a-4f6e-a3b5-7d0c2e9f1a64",
  hijab: "c47a9e03-5b2d-4e81-9f6c-1a3d8b7e2c59",
  queued: "2c3d4e5f-6a7b-4c8d-9e0f-1a2b3c4d5e6f",
  preparing: "4e5f6a7b-8c9d-4e0f-a1b2-c3d4e5f6a7b8",
  ready: "6e5d4c3b-2a19-4f08-b7e6-d5c4b3a29180",
  review: "7f6e5d4c-3b2a-4190-a8f7-e6d5c4b3a291",
  failed: "5f6a7b8c-9d0e-4f1a-b2c3-d4e5f6a7b8c9",
};

const sampleDate = "2026-09-30T18:00:00.000Z";

export const closetV2 = {
  version: 2,
  sampleCatalog: 2,
  photoTipsSeen: true,
  pieces: [
    {
      id: ids.kurta,
      name: "Sage kurta",
      category: "tunic",
      photo: `${ids.kurta}.png`,
      createdAt: "2026-10-01T08:12:41.204Z",
      source: "owned",
      kind: "kurta",
      styles: ["desi"],
      original: `${ids.kurta}-original.jpg`,
      frame: { x: 0.2134, y: 0, width: 0.5732, height: 1 },
    },
    {
      id: ids.shoes,
      name: "Black shoes",
      category: "shoes",
      photo: `${ids.shoes}-original.heic`,
      createdAt: "2026-10-01T08:13:02.871Z",
      source: "owned",
      kind: "shoes",
      styles: ["western", "desi"],
      original: `${ids.shoes}-original.heic`,
    },
    {
      id: ids.hijab,
      name: "Grey jersey hijab",
      category: "hijab",
      photo: "e1d2c3b4-a596-4877-8899-aabbccddeeff.jpg",
      createdAt: "2026-09-30T20:41:15.002Z",
      source: "owned",
    },
    {
      id: "sample-mauve-hijab",
      name: "Mauve chiffon hijab",
      category: "hijab",
      photo: "sample:mauve-hijab",
      createdAt: sampleDate,
      source: "sample",
      kind: "hijab",
      styles: ["western", "desi"],
      traits: {
        tone: "mid",
        occasions: ["work", "everyday", "dinner", "celebration"],
      },
    },
    {
      id: "sample-chocolate-loafers",
      name: "Chocolate leather loafers",
      category: "shoes",
      photo: "sample:chocolate-loafers",
      createdAt: sampleDate,
      source: "sample",
      kind: "shoes",
      styles: ["western", "desi"],
      traits: { tone: "dark", occasions: ["work", "everyday", "dinner"] },
    },
    {
      id: "sample-taupe-bag",
      name: "Taupe everyday bag",
      category: "bag",
      photo: "sample:taupe-bag",
      createdAt: sampleDate,
      source: "sample",
      kind: "bag",
      styles: ["western", "desi"],
      traits: { tone: "mid", occasions: ["work", "everyday", "dinner"] },
    },
    {
      id: "sample-ivory-trousers",
      name: "Ivory wide-leg trousers",
      category: "bottom",
      photo: "sample:ivory-trousers",
      createdAt: sampleDate,
      source: "sample",
      kind: "trousers",
      styles: ["western", "desi"],
      traits: { tone: "light", occasions: ["work", "everyday", "dinner"] },
    },
    {
      id: "sample-olive-maxi-dress",
      name: "My olive dress",
      category: "dress",
      photo: "sample:olive-maxi-dress",
      createdAt: "2026-10-01T09:00:00.000Z",
      source: "sample",
      kind: "dress",
      styles: ["western"],
      traits: { tone: "mid", occasions: ["work", "everyday", "dinner"] },
    },
  ],
  looks: [
    {
      id: "9a7b6c5d-4e3f-4a1b-8c2d-0e1f2a3b4c5d",
      name: "Eid lunch",
      pieceIds: [ids.kurta, "sample-mauve-hijab", ids.shoes],
      createdAt: "2026-10-01T08:20:00.000Z",
    },
    {
      id: "1b2c3d4e-5f6a-4b7c-8d9e-0f1a2b3c4d5e",
      name: "Office Monday",
      pieceIds: [
        "sample-mauve-hijab",
        "sample-olive-maxi-dress",
        "sample-chocolate-loafers",
        "sample-taupe-bag",
      ],
      createdAt: "2026-09-30T21:05:00.000Z",
    },
  ],
  styling: {
    everyday: {
      version: 1,
      occasion: "work",
      style: "western",
      hijab: "always",
      sample: false,
    },
    wardrobe: "owned",
    today: {
      localDate: "2026-10-01",
      timeZone: "Europe/Oslo",
      presetVersion: 1,
      everyday: {
        revision: 4,
        cursor: 2,
        request: {
          occasion: "work",
          style: "western",
          garmentType: null,
          keptIds: [],
          excludedIds: [],
          weather: { source: "unknown" },
          hijab: "always",
          wardrobe: "owned",
        },
        pieceIds: [ids.hijab, ids.shoes],
        previousPieceIds: null,
      },
      occasion: {
        revision: 2,
        cursor: 0,
        request: {
          occasion: "celebration",
          style: "desi",
          garmentType: "kurta",
          keptIds: [ids.kurta],
          excludedIds: [],
          weather: {
            source: "manual",
            warmth: "cold",
            precipitation: "rain",
            exposure: "time-outside",
          },
          hijab: "always",
          wardrobe: "owned",
        },
        pieceIds: [ids.kurta, ids.hijab, ids.shoes],
        previousPieceIds: [ids.kurta, "sample-mauve-hijab", ids.shoes],
      },
      active: "occasion",
    },
  },
  imports: [
    {
      id: ids.queued,
      source: `${ids.queued}-original.heic`,
      createdAt: "2026-10-01T08:30:00.112Z",
      state: "queued",
      attempts: 0,
    },
    {
      id: ids.preparing,
      source: `${ids.preparing}-original.jpg`,
      createdAt: "2026-10-01T08:30:00.115Z",
      state: "preparing",
      attempts: 1,
    },
    {
      id: ids.ready,
      source: `${ids.ready}-original.jpg`,
      createdAt: "2026-10-01T08:30:00.118Z",
      state: "ready",
      attempts: 1,
      prepared: {
        original: `${ids.ready}-original.jpg`,
        cutout: `${ids.ready}.png`,
        thumbnail: `${ids.ready}-thumb.png`,
        frame: { x: 0.1875, y: 0, width: 0.625, height: 1 },
        instances: 1,
        kinds: [
          { kind: "kurta", score: 0.1412 },
          { kind: "tunic", score: 0.1187 },
          { kind: "dress", score: 0.0973 },
          { kind: "abaya", score: 0.0911 },
          { kind: "top", score: 0.0802 },
        ],
        color: [167.2, 174.9, 152.4],
      },
      kind: "kurta",
      name: "Sage kurta",
      alternatives: ["kurta", "tunic", "dress"],
      checks: [],
    },
    {
      id: ids.review,
      source: `${ids.review}-original.jpg`,
      createdAt: "2026-10-01T08:30:00.121Z",
      state: "review",
      attempts: 1,
      prepared: {
        original: `${ids.review}-original.jpg`,
        cutout: null,
        thumbnail: null,
        frame: null,
        instances: 0,
        kinds: [
          { kind: "dupatta", score: 0.1213 },
          { kind: "hijab", score: 0.1179 },
          { kind: "top", score: 0.0911 },
        ],
        color: null,
      },
      kind: "dupatta",
      name: "Dupatta",
      alternatives: ["dupatta", "hijab", "top"],
      checks: ["uncertain", "no-cutout"],
    },
    {
      id: ids.failed,
      source: `${ids.failed}-original.jpg`,
      createdAt: "2026-10-01T08:30:00.124Z",
      state: "failed",
      attempts: 2,
      error: "processing",
    },
  ],
};
