import type { Attributes } from "./attributes";
import type { GarmentKind, Piece, Style } from "./closet";
import { categoryOf } from "./taxonomy";

type Spec = [
  id: string,
  kind: GarmentKind,
  rgb: [number, number, number],
  attributes: Attributes,
  styles?: Style[],
];

const western: Style[] = ["western"];
const desi: Style[] = ["desi"];
const both: Style[] = ["western", "desi"];

const specs: Spec[] = [
  ["black-jersey-hijab", "hijab", [25, 25, 28], { fabric: "jersey" }, both],
  [
    "beige-chiffon-hijab",
    "hijab",
    [214, 196, 170],
    { fabric: "chiffon" },
    both,
  ],
  [
    "dusty-pink-chiffon-hijab",
    "hijab",
    [205, 160, 160],
    { fabric: "chiffon" },
    both,
  ],
  ["navy-modal-hijab", "hijab", [32, 40, 70], { fabric: "modal" }, both],
  ["white-cotton-hijab", "hijab", [240, 240, 236], { fabric: "cotton" }, both],
  ["emerald-satin-hijab", "hijab", [20, 100, 75], { fabric: "satin" }, both],
  [
    "grey-sports-hijab",
    "instant-hijab",
    [120, 120, 125],
    { fabric: "jersey" },
    both,
  ],
  [
    "white-blouse",
    "blouse",
    [242, 240, 235],
    { length: "hip", sleeve: "long", fabric: "cotton", pattern: "solid" },
    western,
  ],
  [
    "black-tshirt",
    "t-shirt",
    [22, 22, 24],
    { length: "hip", sleeve: "short", fabric: "jersey", pattern: "solid" },
    western,
  ],
  [
    "grey-knit-sweater",
    "sweater",
    [140, 138, 135],
    {
      length: "hip",
      sleeve: "long",
      fabric: "knit",
      pattern: "solid",
      volume: "voluminous",
    },
    western,
  ],
  [
    "blue-striped-shirt",
    "shirt",
    [150, 175, 210],
    { length: "hip", sleeve: "long", fabric: "cotton", pattern: "stripe" },
    western,
  ],
  [
    "cream-satin-blouse",
    "blouse",
    [238, 228, 205],
    { length: "hip", sleeve: "long", fabric: "satin", pattern: "solid" },
    western,
  ],
  [
    "black-sports-top",
    "sports-top",
    [20, 20, 22],
    { length: "hip", sleeve: "long", fabric: "jersey" },
    both,
  ],
  [
    "beige-linen-tunic",
    "tunic",
    [210, 195, 170],
    { length: "thigh", sleeve: "long", fabric: "linen", pattern: "solid" },
    western,
  ],
  [
    "black-longline-tunic",
    "tunic",
    [28, 28, 30],
    { length: "knee", sleeve: "long", fabric: "jersey", pattern: "solid" },
    western,
  ],
  [
    "white-lawn-kurta",
    "kurta",
    [244, 242, 236],
    {
      length: "knee",
      sleeve: "long",
      fabric: "lawn",
      pattern: "solid",
      embellishment: "light",
    },
    desi,
  ],
  [
    "teal-printed-kurti",
    "kurti",
    [30, 120, 125],
    {
      length: "hip",
      sleeve: "long",
      fabric: "cotton",
      pattern: "print",
      scale: "small",
    },
    desi,
  ],
  [
    "maroon-embroidered-kameez",
    "kameez",
    [110, 20, 35],
    {
      length: "knee",
      sleeve: "long",
      fabric: "chiffon",
      pattern: "embroidered",
      embellishment: "heavy",
    },
    desi,
  ],
  [
    "black-maxi-dress",
    "dress",
    [24, 24, 26],
    {
      length: "ankle",
      sleeve: "long",
      fabric: "jersey",
      pattern: "solid",
      volume: "straight",
    },
    western,
  ],
  [
    "floral-maxi-dress",
    "dress",
    [190, 120, 140],
    {
      length: "ankle",
      sleeve: "long",
      fabric: "chiffon",
      pattern: "print",
      scale: "medium",
    },
    western,
  ],
  [
    "emerald-satin-gown",
    "dress",
    [18, 95, 70],
    {
      length: "ankle",
      sleeve: "long",
      fabric: "satin",
      pattern: "solid",
      embellishment: "light",
    },
    western,
  ],
  [
    "navy-shirt-dress",
    "dress",
    [35, 45, 80],
    { length: "calf", sleeve: "long", fabric: "cotton", pattern: "solid" },
    western,
  ],
  [
    "blue-jeans",
    "jeans",
    [70, 95, 140],
    { length: "ankle", fabric: "denim", volume: "straight" },
    western,
  ],
  [
    "black-trousers",
    "trousers",
    [26, 26, 28],
    { length: "ankle", fabric: "wool", volume: "straight" },
    both,
  ],
  [
    "beige-wide-leg",
    "wide-leg",
    [205, 190, 165],
    { length: "ankle", fabric: "linen", volume: "voluminous" },
    western,
  ],
  [
    "black-maxi-skirt",
    "skirt",
    [28, 28, 30],
    { length: "ankle", fabric: "chiffon", volume: "voluminous" },
    western,
  ],
  [
    "grey-joggers",
    "joggers",
    [110, 110, 115],
    { length: "ankle", fabric: "jersey" },
    both,
  ],
  [
    "white-shalwar",
    "shalwar",
    [244, 242, 236],
    { length: "ankle", fabric: "lawn", volume: "voluminous" },
    desi,
  ],
  [
    "gold-sharara",
    "sharara",
    [200, 165, 90],
    {
      length: "ankle",
      fabric: "chiffon",
      volume: "voluminous",
      embellishment: "heavy",
    },
    desi,
  ],
  [
    "gold-dupatta",
    "dupatta",
    [205, 170, 95],
    { fabric: "chiffon", embellishment: "light" },
    desi,
  ],
  [
    "black-blazer",
    "blazer",
    [24, 24, 26],
    { length: "hip", sleeve: "long", fabric: "wool" },
    western,
  ],
  [
    "beige-cardigan",
    "cardigan",
    [200, 180, 150],
    { length: "thigh", sleeve: "long", fabric: "knit" },
    both,
  ],
  [
    "denim-jacket",
    "jacket",
    [80, 110, 150],
    { length: "hip", sleeve: "long", fabric: "denim" },
    western,
  ],
  [
    "black-open-abaya",
    "abaya",
    [20, 20, 22],
    {
      length: "ankle",
      sleeve: "long",
      fabric: "chiffon",
      volume: "voluminous",
    },
    both,
  ],
  [
    "camel-coat",
    "coat",
    [180, 140, 95],
    { length: "knee", sleeve: "long", fabric: "wool" },
    both,
  ],
  ["white-sneakers", "sneakers", [245, 245, 245], {}, both],
  ["black-ankle-boots", "boots", [22, 22, 24], {}, both],
  ["nude-heels", "heels", [215, 180, 150], {}, both],
  ["gold-khussa", "khussa", [200, 165, 90], { embellishment: "light" }, desi],
  ["black-loafers", "loafers", [24, 24, 26], {}, western],
  ["black-tote", "tote", [26, 26, 28], {}, both],
  ["gold-clutch", "clutch", [205, 170, 95], {}, both],
  ["tan-crossbody", "crossbody", [165, 115, 75], {}, both],
];

const title = (id: string) =>
  id.charAt(0).toUpperCase() + id.slice(1).replace(/-/g, " ");

export const realisticPieces: Piece[] = specs.map(
  ([id, kind, rgb, attributes, styles]) => ({
    id: `real-${id}`,
    name: title(id),
    category: categoryOf(kind),
    kind,
    photo: `${id}.png`,
    createdAt: "2026-09-20T08:00:00.000Z",
    source: "owned",
    ...(styles ? { styles } : {}),
    ...(kind === "abaya" ? { traits: { open: true } } : {}),
    attributes,
    colors: [{ rgb, share: 1 }],
  }),
);
