export const theme = {
  colors: {
    canvas: "#FFFFFF",
    surface: "#FBF9F7",
    sunken: "#F2EDE7",
    ink: "#322E28",
    inkMuted: "#706963",
    inkDisabled: "#706963",
    placeholder: "#706963",
    line: "#E6E0DC",
    lineField: "#948B85",
    plum: "#675469",
    plumPressed: "#574559",
    plumSoft: "#F3EEF4",
    plumSoftPressed: "#E6DDE7",
    plumSoftDeep: "#DDD2DF",
    onPlum: "#FFFFFF",
    blush: "#E2B1A8",
    blushStrong: "#BE8077",
    blushEdge: "#9A5A52",
    paper: "#FEF6DE",
    error: "#96354A",
    scrim: "rgba(50,46,40,0.55)",
    scrimPill: "rgba(50,46,40,0.70)",
    onMedia: "#FFFFFF",
  },
  colorsIncreasedContrast: { inkMuted: "#322E28", line: "#948B85" },
  brand: { ivory: "#F4EDE3", plumGround: "#644E64", sheen: "#FAF8F3" },
  space: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, footerInset: 48 },
  radius: { sm: 8, md: 12, lg: 20, full: 999 },
  type: {
    display: {
      fontFamily: "Georgia",
      fontSize: 34,
      lineHeight: 41,
      letterSpacing: -0.4,
      maxFontSizeMultiplier: 2,
    },
    title: {
      fontFamily: "Georgia",
      fontSize: 26,
      lineHeight: 32,
      letterSpacing: -0.2,
      maxFontSizeMultiplier: 2,
    },
    headline: { fontSize: 17, lineHeight: 22, fontWeight: "600" },
    body: { fontSize: 17, lineHeight: 24 },
    subhead: { fontSize: 15, lineHeight: 20 },
    footnote: { fontSize: 13, lineHeight: 18 },
    mark: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: "600",
      maxFontSizeMultiplier: 1.4,
    },
  },
  elevation: {
    flat: {},
    rest: {
      shadowColor: "#322E28",
      shadowOpacity: 0.1,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 3 },
    },
    lift: {
      shadowColor: "#322E28",
      shadowOpacity: 0.14,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
  },
  size: {
    touch: 44,
    controlRegular: 52,
    controlSmall: 44,
    iconInline: 17,
    iconBar: 22,
    thumb: 40,
    swatch: 14,
    swatchLarge: 44,
    faceCircle: 264,
    brandMark: 96,
  },
} as const;

export type Colors = Record<keyof typeof theme.colors, string>;

export function gutterFor(windowWidth: number): 16 | 20 {
  return windowWidth >= 428 ? 20 : 16;
}
