KINDS = {
 "hijab": ("hijab", ["a folded hijab headscarf", "a chiffon scarf", "a knitted scarf"]),
 "top": ("top", ["a blouse", "a t-shirt", "a shirt"]),
 "tunic": ("tunic", ["a long tunic top"]),
 "kurta": ("tunic", ["an embroidered kurta, a long South Asian tunic", "a kameez"]),
 "trousers": ("bottom", ["a pair of trousers", "a pair of jeans"]),
 "shalwar": ("bottom", ["salwar trousers, loose gathered South Asian trousers"]),
 "skirt": ("bottom", ["a long skirt"]),
 "dress": ("dress", ["a long dress", "a maxi dress", "a gown"]),
 "abaya": ("dress", ["an abaya, a long loose robe", "a kaftan"]),
 "blazer": ("layer", ["a blazer jacket", "a suit jacket"]),
 "cardigan": ("layer", ["a knit cardigan sweater"]),
 "jacket": ("layer", ["a jacket"]),
 "coat": ("layer", ["a coat", "a cape"]),
 "shoes": ("shoes", ["a pair of shoes", "a pair of loafers", "a pair of sneakers", "a pair of heels"]),
 "boots": ("shoes", ["a pair of boots"]),
 "bag": ("bag", ["a handbag", "a leather bag"]),
 "dupatta": ("accessory", ["a long dupatta shawl"]),
}
