DESI = ["desi"]
BOTH = ["western", "desi"]

KINDS = {
 "hijab": ("hijab", BOTH, ["a folded hijab headscarf", "a chiffon hijab scarf", "a jersey hijab"]),
 "instant-hijab": ("hijab", BOTH, ["an instant slip-on hijab with a sewn face opening", "a pull-on one-piece hijab"]),
 "underscarf": ("hijab", BOTH, ["a tube underscarf hijab cap", "a fitted bonnet underscarf"]),
 "shawl": ("hijab", BOTH, ["a wide woven shawl", "a knitted winter scarf", "a pashmina wrap"]),
 "blouse": ("top", None, ["a blouse", "a silk blouse"]),
 "shirt": ("top", None, ["a button-up collared shirt"]),
 "t-shirt": ("top", None, ["a t-shirt"]),
 "sweater": ("top", None, ["a knitted sweater", "a pullover jumper"]),
 "top": ("top", None, ["a top", "a sleeveless top"]),
 "kurta": ("tunic", DESI, ["an embroidered kurta, a long South Asian tunic"]),
 "kurti": ("tunic", DESI, ["a short kurti, a hip-length South Asian tunic"]),
 "kameez": ("tunic", DESI, ["a kameez, the long tunic of a shalwar kameez suit"]),
 "tunic": ("tunic", None, ["a long tunic top"]),
 "trousers": ("bottom", None, ["a pair of trousers", "a pair of tailored pants"]),
 "jeans": ("bottom", None, ["a pair of blue denim jeans"]),
 "wide-leg": ("bottom", None, ["a pair of wide-leg palazzo trousers"]),
 "shalwar": ("bottom", DESI, ["salwar trousers, loose gathered South Asian trousers"]),
 "churidar": ("bottom", DESI, ["churidar trousers, tight South Asian trousers gathered at the ankle"]),
 "sharara": ("bottom", DESI, ["sharara trousers, flared from the knee"]),
 "gharara": ("bottom", DESI, ["gharara trousers, gathered and flared at the knee with a band"]),
 "lehenga": ("bottom", DESI, ["a lehenga, a long embroidered South Asian skirt"]),
 "skirt": ("bottom", None, ["a long skirt", "a midi skirt"]),
 "dress": ("dress", None, ["a long dress", "a maxi dress", "a gown"]),
 "anarkali": ("dress", DESI, ["an anarkali, a long flared South Asian frock"]),
 "abaya": ("dress", None, ["an abaya, a long loose robe"]),
 "kaftan": ("dress", None, ["a kaftan, a loose wide-sleeved robe"]),
 "blazer": ("layer", None, ["a blazer jacket", "a suit jacket"]),
 "cardigan": ("layer", BOTH, ["a knit cardigan sweater"]),
 "jacket": ("layer", None, ["a jacket", "a denim jacket"]),
 "coat": ("layer", BOTH, ["a coat", "a cape"]),
 "waistcoat": ("layer", None, ["a sleeveless waistcoat vest"]),
 "sneakers": ("shoes", BOTH, ["a pair of sneakers"]),
 "flats": ("shoes", BOTH, ["a pair of ballet flats"]),
 "loafers": ("shoes", None, ["a pair of loafers"]),
 "heels": ("shoes", BOTH, ["a pair of high heels", "a pair of heeled shoes"]),
 "sandals": ("shoes", None, ["a pair of sandals"]),
 "khussa": ("shoes", DESI, ["a pair of khussa, embroidered South Asian slip-on shoes with a pointed toe"]),
 "boots": ("shoes", BOTH, ["a pair of boots", "a pair of ankle boots"]),
 "handbag": ("bag", BOTH, ["a handbag", "a leather handbag"]),
 "tote": ("bag", BOTH, ["a tote bag"]),
 "crossbody": ("bag", BOTH, ["a crossbody bag with a long strap", "a leather satchel"]),
 "clutch": ("bag", BOTH, ["a small clutch purse"]),
 "backpack": ("bag", BOTH, ["a backpack"]),
 "dupatta": ("accessory", DESI, ["a long dupatta shawl"]),
 "jewellery": ("accessory", BOTH, ["a piece of jewellery", "a necklace and earrings"]),
 "belt": ("accessory", BOTH, ["a belt"]),
}

STYLES = {
 "desi": ["a South Asian embroidered garment", "a Pakistani or Indian outfit piece"],
 "western": ["a Western garment", "a plain Western fashion piece"],
}
